export const items = [
  {
    id: "1",
    category: "tech",
    image: "/Selling/used_Macbook.jpg",
    title: "Macbook Pro",
    originalPrice: 1299,
    salePrice: 999,
  },
  {
    id: "2",
    category: "furniture",
    image: "/Selling/grey_couch.jpg",
    title: "Grey Couch",
    salePrice: 70,
  },
  {
    id: "3",
    category: "textbooks",
    image: "/Selling/dental_textbook.jpg",
    title: "Dental Hygiene Textbook",
    originalPrice: 300,
    salePrice: 250,
  },
  {
    id: "4",
    category: "furniture",
    image: "/Selling/dresser.jpg",
    title: "White Dresser",
    salePrice: 20,
  },
  {
    id: "5",
    category: "textbooks",
    image: "/Selling/human_anatomy_textbook.jpg",
    title: "Human Anatomy Textbook",
    salePrice: 50,
  },
  {
    id: "6",
    category: "tech",
    image: "/Selling/beats.jpg",
    title: "Beats Solo 3",
    originalPrice: 100,
    salePrice: 80,
  },
  {
    id: "7",
    category: "furniture",
    image: "/Selling/table.jpg",
    title: "Table",
    salePrice: 60,
  },
  {
    id: "8",
    category: "textbooks",
    image: "/Selling/nursing_textbook.jpg",
    title: "Nursing Textbook",
    salePrice: 60,
  },
  {
    id: "9",
    category: "apparel",
    image: "/Selling/backpack.jpg",
    title: "Kanken Backpacks",
    salePrice: 30,
  },
  {
    id: "10",
    category: "household",
    image: "/Selling/rice_cooker.jpg",
    title: "Rice Cooker",
    originalPrice: 30,
    salePrice: 20,
  },
];
